baseURL = "/"
languageCode = "en-us"
title = "{{ .SiteName }}"
theme = "hugo-creative-portfolio-theme"

[params]
  description = "{{ .SiteDescription }}"
  style = "default"
  
  # Portfolio settings
  email = "your-email@example.com"
  showProjectsLink = true
  
  # Social media links
  linkedin = ""
  github = ""
  twitter = ""

[menu]
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3
