version: '3.8'

services:
  frontend:
    build: 
      context: ./ai-hugo-frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      - backend
    volumes:
      - ./volumes/user_uploads:/app/uploads
    networks:
      - hugo-network

  backend:
    build:
      context: ./ai-hugo-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
      - LLM_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - ./volumes/generated_sites:/app/generated_sites
    networks:
      - hugo-network

  hugo-builder:
    build:
      context: ./hugo-builder
      dockerfile: Dockerfile
    volumes:
      - ./volumes/generated_sites:/sites
    networks:
      - hugo-network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./volumes/generated_sites:/usr/share/nginx/html/sites:ro
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - hugo-builder
    networks:
      - hugo-network
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    networks:
      - hugo-network
    deploy:
      resources:
        limits:
          memory: 4G

networks:
  hugo-network:
    driver: bridge
