baseURL = "/"
languageCode = "en-us"
title = "{{ .SiteName }}"
theme = "PaperMod"

[params]
  description = "{{ .SiteDescription }}"
  author = "AI Hugo Generator"
  
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
