baseURL = "/"
languageCode = "en-us"
title = "{{ .SiteName }}"
theme = "hugo-book"

[params]
  description = "{{ .SiteDescription }}"
  # Book theme settings
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookComments = false
  
[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/docs/"
    weight = 1
  [[menu.main]]
    identifier = "api"
    name = "API"
    url = "/api/"
    weight = 2
  [[menu.main]]
    identifier = "examples"
    name = "Examples"
    url = "/examples/"
    weight = 3
  [[menu.main]]
    identifier = "support"
    name = "Support"
    url = "/support/"
    weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
